#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use LiquidLight\YamlLint\Command\YamlLintCommand;

$application = new Application();
$application->add((new YamlLintCommand(__DIR__))->setAliases(['run']));
$application->run();
