filePatterns:
  - "*.ts"
  - "*.typoscript"
  - "setup.txt"
  - "constants.txt"

paths:
  - "./"

sniffs:
  - class: Indentation
    parameters:
      useSpaces: false
      indentPerLevel: 1
      indentConditions: true

  - class: RepeatingRValue
    disabled: true
