#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use LiquidLight\TypoScriptLint\Command\TypoScriptLintCommand;

$application = new Application();
$application->add((new TypoScriptLintCommand(__DIR__))->setAliases(['run']));
$application->run();
