#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use LiquidLight\PhpStan\Command\PhpStanCommand;

$application = new Application();
$application->add((new PhpStanCommand(__DIR__))->setAliases(['run']));
$application->run();
