#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use LiquidLight\Stylelint\Command\StylelintCommand;

$application = new Application();
$application->add((new StylelintCommand(__DIR__))->setAliases(['run']));
$application->run();
