#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use LiquidLight\JsonLint\Command\JsonLintCommand;

$application = new Application();
$application->add((new JsonLintCommand(__DIR__))->setAliases(['run']));
$application->run();
