#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use LiquidLight\Eslint\Command\EslintCommand;

$application = new Application();
$application->add((new EslintCommand(__DIR__))->setAliases(['run']));
$application->run();
