#!/usr/bin/env php
<?php

include $_composer_autoload_path ?? __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use LintKit\Eslint\Command\EslintCommand;

$run = new EslintCommand(__DIR__);
$application = new Application();
$application->add($run);
$application->setDefaultCommand($run->getName());
$application->run();
