#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use LiquidLight\Rector\Command\PhpRectorCommand;
use LiquidLight\Rector\Command\PhpRectorTypo3Command;

$application = new Application();
$application->add((new PhpRectorCommand(__DIR__))->setAliases(['run']));
$application->add((new PhpRectorTypo3Command(__DIR__))->setAliases(['run']));
$application->run();
